name: sample-dockerfile-static
static_sites:
  - name: web
    github:
      deploy_on_push: true
      branch: main
      repo: hxmtl/sample-dockerfile-static
    dockerfile_path: Dockerfile.static
    output_dir: /app/public
